// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerwisSamochodowy.Models;

#nullable disable

namespace SerwisSamochodowy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513132626_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SerwisSamochodowy.Models.Mechanic", b =>
                {
                    b.Property<int>("IdMechanic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMechanic");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Parts", b =>
                {
                    b.Property<int>("IdPart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPart");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Repairment", b =>
                {
                    b.Property<int>("IdRepairment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdMechanic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MechanicIdMechanic")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleIdVehicle")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRepairment");

                    b.HasIndex("MechanicIdMechanic");

                    b.HasIndex("VehicleIdVehicle");

                    b.ToTable("Repairments");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.RepairmentParts", b =>
                {
                    b.Property<int>("IdRepairment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRepairment", "IdPart");

                    b.HasIndex("IdPart");

                    b.ToTable("RepairmentParts");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Users", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Vehicle", b =>
                {
                    b.Property<int>("IdVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdVehicle");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Repairment", b =>
                {
                    b.HasOne("SerwisSamochodowy.Models.Mechanic", "Mechanic")
                        .WithMany("Repairments")
                        .HasForeignKey("MechanicIdMechanic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerwisSamochodowy.Models.Vehicle", "Vehicle")
                        .WithMany("Repairments")
                        .HasForeignKey("VehicleIdVehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.RepairmentParts", b =>
                {
                    b.HasOne("SerwisSamochodowy.Models.Parts", "Part")
                        .WithMany("RepairmentParts")
                        .HasForeignKey("IdPart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerwisSamochodowy.Models.Repairment", "Repairment")
                        .WithMany("RepairmentParts")
                        .HasForeignKey("IdRepairment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Repairment");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Mechanic", b =>
                {
                    b.Navigation("Repairments");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Parts", b =>
                {
                    b.Navigation("RepairmentParts");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Repairment", b =>
                {
                    b.Navigation("RepairmentParts");
                });

            modelBuilder.Entity("SerwisSamochodowy.Models.Vehicle", b =>
                {
                    b.Navigation("Repairments");
                });
#pragma warning restore 612, 618
        }
    }
}
